name: Update LLVM from upstream - Test

on:
  workflow_dispatch:

jobs:
  update-llvm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "me@herobuxx.me"
          git config --global user.name "HeroBuxx"

      - name: Pull changes from upstream and Push
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git clone https://github.com/liliumproject/llvm-project
          cd llvm-project
          git remote add upstream https://github.com/llvm/llvm-project.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git remote set-url origin https://herobuxx:${PUSH_TOKEN}@github.com/liliumproject/llvm-project.git
          git push origin main